
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-05
owner: ucsb-cs156-s25
repo_name: team01-s25-05
pull_requests: [{"author":{"id":"U_kgDOBm9Hyw","is_bot":false,"login":"SnowyMAT","name":""},"headRefName":"MT-MenuItemReview-single-GET","number":46,"title":"Added single record GET endpoint for MenuItemReview","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/46"},{"author":{"id":"MDQ6VXNlcjY3ODg2NTM4","is_bot":false,"login":"VishalSeeni-108","name":"Vishal S."},"headRefName":"vs-Articles-create-db","number":45,"title":"Adding new database table for Articles","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/45"},{"author":{"id":"U_kgDOBm9Hyw","is_bot":false,"login":"SnowyMAT","name":""},"headRefName":"MT-MenuItemReview-create-controller","number":44,"title":"MenuItemReview create controller, get all, post methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/44"}]
