
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-05
owner: ucsb-cs156-s25
repo_name: team01-s25-05
pull_requests: [{"author":{"id":"U_kgDOB2-rTg","is_bot":false,"login":"hienhuynh2026","name":""},"headRefName":"hienhuynh2026-delete-for-recommendationrequest","number":61,"title":"Hienhuynh2026 delete for recommendationrequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/61"},{"author":{"id":"MDQ6VXNlcjgxMzQ1NzUw","is_bot":false,"login":"AwinZhang1","name":"Awin Zhang"},"headRefName":"Awin-HelpRequest-Delete","number":60,"title":"Awin help request delete","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/60"},{"author":{"id":"U_kgDOB2-rTg","is_bot":false,"login":"hienhuynh2026","name":""},"headRefName":"hienhuynh2026-put-for-recommendationrequest","number":59,"title":"Hienhuynh2026 put for recommendationrequest","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/59"},{"author":{"id":"U_kgDOB2-rTg","is_bot":false,"login":"hienhuynh2026","name":""},"headRefName":"hienhuynh2026-recommendationrequest-get-by-id","number":58,"title":"Hienhuynh2026 recommendationrequest get by id for recommendation request ","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/58"},{"author":{"id":"MDQ6VXNlcjY3ODg2NTM4","is_bot":false,"login":"VishalSeeni-108","name":"Vishal S."},"headRefName":"VS-Articles-Add-Get-Show","number":54,"title":"Added GET (show) endpoint and tests","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/54"}]
