
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-05
owner: ucsb-cs156-s25
repo_name: team01-s25-05
pull_requests: [{"author":{"id":"MDQ6VXNlcjgxMzQ1NzUw","is_bot":false,"login":"AwinZhang1","name":"Awin Zhang"},"headRefName":"Awin-HelpRequest-create-db","number":50,"title":"Closes #2","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/50"},{"author":{"id":"U_kgDOB2-rTg","is_bot":false,"login":"hienhuynh2026","name":""},"headRefName":"hienhuynh2026-create-db-table-commits","number":49,"title":"hienhuynh2026 - create database table for recommendation request","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/49"},{"author":{"id":"U_kgDOBm9Hyw","is_bot":false,"login":"SnowyMAT","name":""},"headRefName":"MT-MenuItemReview-single-DELETE","number":48,"title":"Added DELETE endpoint for single record in MenuItemReview database table","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/48"},{"author":{"id":"U_kgDOBm9Hyw","is_bot":false,"login":"SnowyMAT","name":""},"headRefName":"MT-MenuItemReview-single-PUT","number":47,"title":"Added single PUT endpoint for Menu Item Review","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/47"},{"author":{"id":"U_kgDOBm9Hyw","is_bot":false,"login":"SnowyMAT","name":""},"headRefName":"MT-MenuItemReview-single-GET","number":46,"title":"Added single record GET endpoint for MenuItemReview","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/46"},{"author":{"id":"U_kgDOBm9Hyw","is_bot":false,"login":"SnowyMAT","name":""},"headRefName":"MT-MenuItemReview-create-controller","number":44,"title":"MenuItemReview create controller, get all, post methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/44"}]
