
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-05
owner: ucsb-cs156-s25
repo_name: team01-s25-05
pull_requests: [{"author":{"id":"U_kgDOBm9Hyw","is_bot":false,"login":"SnowyMAT","name":""},"headRefName":"MT-MenuItemReview-create-controller","number":44,"title":"MenuItemReview create controller, get all, post methods","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/44"},{"author":{"id":"U_kgDOBm9Hyw","is_bot":false,"login":"SnowyMAT","name":""},"headRefName":"MT-MenuItemReview-create-db","number":43,"title":"MT - create MenuItemReview database table","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/43"}]
