
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team01-s25-05
owner: ucsb-cs156-s25
repo_name: team01-s25-05
pull_requests: [{"author":{"id":"U_kgDOB2-rTg","is_bot":false,"login":"hienhuynh2026","name":""},"headRefName":"hienhuynh2026-create-recommendationrequest-controller","number":57,"title":"Hienhuynh2026 create recommendationrequest controller","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/57"},{"author":{"id":"MDQ6VXNlcjY3NzI0NTIw","is_bot":false,"login":"austish","name":"Austin Quach"},"headRefName":"Austin-UCSBDiningCommonsMenuItems","number":56,"title":"Created database table for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/56"},{"author":{"id":"MDQ6VXNlcjgxMzQ1NzUw","is_bot":false,"login":"AwinZhang1","name":"Awin Zhang"},"headRefName":"Awin-HelpRequest-Put","number":55,"title":"Awin help request put","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/55"},{"author":{"id":"MDQ6VXNlcjY3ODg2NTM4","is_bot":false,"login":"VishalSeeni-108","name":"Vishal S."},"headRefName":"VS-Articles-Add-Get-Show","number":54,"title":"Added GET (show) endpoint and tests","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/54"},{"author":{"id":"MDQ6VXNlcjgxMzQ1NzUw","is_bot":false,"login":"AwinZhang1","name":"Awin Zhang"},"headRefName":"Awin-HelpRequest-Get","number":53,"title":"Awin-HelpRequest-Get Closes #4","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/53"},{"author":{"id":"U_kgDOBm9Hyw","is_bot":false,"login":"SnowyMAT","name":""},"headRefName":"MT-MenuItemReview-single-DELETE","number":48,"title":"Added DELETE endpoint for single record in MenuItemReview database table","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/48"},{"author":{"id":"U_kgDOBm9Hyw","is_bot":false,"login":"SnowyMAT","name":""},"headRefName":"MT-MenuItemReview-single-PUT","number":47,"title":"Added single PUT endpoint for Menu Item Review","url":"https://github.com/ucsb-cs156-s25/team01-s25-05/pull/47"}]
